### ISSUE TITLE
How can i run it

### ISSUE THREAD

**Issue by ankitsiliconithub** [tolgatasci/musically-tiktok-api-python#2]
Hi,
 Can you Please tell me how can i run it because when i run in my terminal it throw me 
Traceback (most recent call last):
  File "demo.py", line 1, in <module>

Thanks in advance.

**Comment by tolgatasci** [comment]
python version ?

**Comment by ankitsiliconithub** [comment]
Python 3.7.1

**Comment by ankitsiliconithub** [comment]
some configuration issue from my side

**Comment by Gautamshahi** [comment]
Did you able to solve the issue?
