### ISSUE TITLE
Do not login

### ISSUE THREAD

**Issue by danclas** [tolgatasci/musically-tiktok-api-python#4]
Maybe it is my problem, but I can't login in my account

**Comment by tolgatasci** [comment]
No email 
username && password

**Comment by danclas** [comment]
> No email
> username && password
Anyway dont work. Pleas check

**Comment by tolgatasci** [comment]
how can I check without seeing the error?

**Comment by danclas** [comment]
Not get error, just not authorization

**Comment by tolgatasci** [comment]
api.py
login = self.helper.request_post(url,posts)
print(login.json())

real error

**Comment by tolgatasci** [comment]
for this I can manually adjust the captcha. However, I'm going to work with artificial intelligence for auto.

**Comment by danclas** [comment]
> for this I can manually adjust the captcha. However, I'm going to work with artificial intelligence for auto.

Hot do this manually?

**Comment by HuyQLuong** [comment]
@tolgatasci  could you have a instruction about how we can adjust it manually. It seems different from the tutorial you provide about creating the account. Thank you !

**Comment by panamantis** [comment]
FYI: the anti-captcha.com site can break those captchas. $1 for 1000.
