### ISSUE TITLE
After 10 likes, the API stops working for 5-10 minutes

### ISSUE THREAD

**Issue by dixakman** [tolgatasci/musically-tiktok-api-python#5]
Made a bot on the phone application for signing requests. I try to put 20 likes from 20 different accounts, only 10 are put in the end, the rest comes with the answer is_digg = 1 (I’m not set), after 5-10 minutes if I repeat the procedure, it works again, and only 10 again. Someone you know in what's the problem?

**Comment by tolgatasci** [comment]
rope blocking. however, the parameters you use may cause this. Creating parameters I haven't found yet. These parameters are as follows.

AS
CP
MAS

**Comment by panamantis** [comment]
These are part of the anti-spam security system.  To create them, you'll need to run an android emulator and run their signing url.  Not easy, but I've done it.

**Comment by dixakman** [comment]
I made the signing of requests on the emulator, but the problem is the same!

The strangest thing is that if you log in from a real phone, you can put a Like without problems.

**Comment by tolgatasci** [comment]
your need as,cp,mas new version algorithm. NO old bypass. your algorithm old ? contact mail

**Comment by dixakman** [comment]
our algorithm was made based on version 9.3.0 android

**Comment by tolgatasci** [comment]
@dixakman  contact me please tolgatasci1@gmail.com 
Send me an as cp mas parameter as an example.

**Comment by umeshdepale** [comment]
Hello how you use the cokkie i can get all the data from proxy and also get cookie but how to use this please help me
