### ISSUE TITLE
Error after typing the captcha

### ISSUE THREAD

**Issue by Brain2998** [tolgatasci/musically-tiktok-api-python#8]
**Describe the bug**
I have registered  on TikTok via Android version. When i tries to login with existing credentials i receive the captcha in response. After using code from demo.py and typing the captcha i received an error in response. 
`{'data': {'captcha': '', 'description': 'Kullanıcı yok', 'error_code': 1011}, 'message': 'error'}`
`{'data': {'user_id': None, 'session_key': None, 'screen_name': None}, 'cookies': {'odin_tt': '###'}`
What can encounter such error? Also i delete api.global_variable['device_id'] declaration, and same for 'iid' and 'openudid' from demo.py example, because with it i can not even receive the captcha.

**To Reproduce**
1. Running the code:

`import api`
`import captcha`
`from capthca import capthca`

`test=api.api()`
`login=test.login('###', '###')`
`cc=capthca(login.get('code'))`
`test.login('###', '###', cc.backdata)`
2. Typing the captcha from window appeared.
2. Receive an error in response:
`{'data': {'captcha': '', 'description': 'Kullanıcı yok', 'error_code': 1011}, 'message': 'error'}`
`{'data': {'user_id': None, 'session_key': None, 'screen_name': None}, 'cookies': {'odin_tt': '###'}`
**Expected behavior**
Successfully log in.

**Additional context**
Seems like error description not properly decided? Or it is TikTok issue

**Comment by Brain2998** [comment]
Sorry for an issue. Problem was that i sending email to login() method, not username. Maybe it will help someone.

**Comment by umeshdepale** [comment]
Hello i can try your code but it show me error 

{'data': {'captcha': '', 'description': '', 'error_code': 1105}, 'message': 'error'}
Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    cc = capthca(login.get('code'))
  File "C:\Users\Win10\Downloads\tiktok\capthca.py", line 19, in __init__
    self.display_image()
  File "C:\Users\Win10\Downloads\tiktok\capthca.py", line 31, in display_image
    img =  PhotoImage(data=self.datam)
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3545, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\Win10\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 3501, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: value for "-data" missing

can you help me how to successfully login on tiktok or can you give me your data whcih you receive after login so i can put my values here please help

**Comment by artemfind5** [comment]
I have the same problem as **umeshdepale**. **Brain2998** please help
